name: Bug Report
title: '[BUG Report] '
description: Report a bug to help us improve
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/ittuann/obsidian-gpt-liteinquirer-plugin/labels/bug) about this problem first.
        2. Make sure it's an issue with Tauri and not something else you are using.
        3. Remember to follow our community guidelines and be friendly.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: textarea
    id: info
    attributes:
      label: Information
      description: "Platform and version and other information that may be helpful."
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Stack trace
      render: text

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
