name: FOSSA Analysis

on:
  push:
    branches:
      - main

jobs:
  fossa:
    runs-on: ubuntu-latest
    environment: staging

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run FOSSA Scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API }}
